"use client";
import { useState } from "react";
import Link from "next/link";
import { ciptaAktiviti,tambahPesertaAktiviti,pesertaAktiviti,jawapanAktiviti,tutupAktiviti,suntingAktiviti,padamAktiviti,padamJawapanAktiviti } from "@/lib/borang-aktiviti";
import type { AktivitiBorang, JawapanAktiviti } from "@/data/borang-aktiviti";
import CetakAkuan from "@/components/CetakAkuan";
type Peserta={murid_id:string;nama:string;no_kp:string;kelas:string};
export default function Panel({senarai,skop}:{senarai:AktivitiBorang[];skop:string[]}){
 const [semua,setSemua]=useState(senarai);const [pilih,setPilih]=useState<AktivitiBorang|null>(null);
 const [peserta,setPeserta]=useState<Peserta[]>([]);const [jawapan,setJawapan]=useState<JawapanAktiviti[]>([]);
 const [teks,setTeks]=useState("");const [semak,setSemak]=useState<Peserta[]|null>(null);
 const [nota,setNota]=useState("");const [sibuk,setSibuk]=useState(false);const [cetak,setCetak]=useState<JawapanAktiviti|null>(null);
 async function cipta(fd:FormData){setSibuk(true);setNota("");try{const v=(k:string)=>String(fd.get(k)??"");const r=await ciptaAktiviti({nama:v('nama'),tarikh:v('tarikh'),masa:v('masa'),tempat:v('tempat'),anjuran:v('anjuran'),tutup:v('tutup'),skop:v('skop')});setNota(r.mesej);if(r.rekod)setSemua(s=>[r.rekod!,...s]);}catch(e){setNota(e instanceof Error?e.message:'Gagal mencipta aktiviti.')}finally{setSibuk(false)}}
 async function buka(a:AktivitiBorang){setSibuk(true);setNota("");setCetak(null);setSemak(null);setTeks("");setPilih(null);try{const [p,j]=await Promise.all([pesertaAktiviti(a.id),jawapanAktiviti(a.id)]);setPeserta(p);setJawapan(j);setPilih(a);}catch(e){setNota(e instanceof Error?e.message:'Gagal membaca aktiviti.')}finally{setSibuk(false)}}
 async function importPeserta(simpan:boolean){if(!pilih)return;setSibuk(true);try{const r=await tambahPesertaAktiviti(pilih.id,teks,simpan);setNota(r.mesej);if(r.ok&&r.peserta){if(simpan){setPeserta(await pesertaAktiviti(pilih.id));setSemak(null);setTeks("");}else setSemak(r.peserta);}}catch(e){setNota(e instanceof Error?e.message:'Gagal import.')}finally{setSibuk(false)}}
 async function tutup(){if(!pilih)return;setSibuk(true);try{await tutupAktiviti(pilih.id);setSemua(s=>s.map(a=>a.id===pilih.id?{...a,aktif:false}:a));setPilih({...pilih,aktif:false});setNota('Borang ditutup. Rekod dan cetakan kekal.');}catch(e){setNota(e instanceof Error?e.message:'Gagal menutup borang.')}finally{setSibuk(false)}}
 async function sunting(fd:FormData){if(!pilih)return;setSibuk(true);try{const v=(k:string)=>String(fd.get(k)??"");const r=await suntingAktiviti(pilih.id,{nama:v('nama'),tarikh:v('tarikh'),masa:v('masa'),tempat:v('tempat'),anjuran:v('anjuran'),tutup:v('tutup')});setNota(r.mesej);if(r.ok&&r.rekod){setPilih(r.rekod);setSemua(s=>s.map(a=>a.id===r.rekod!.id?r.rekod!:a));}}catch(e){setNota(e instanceof Error?e.message:'Gagal menyunting aktiviti.')}finally{setSibuk(false)}}
 async function padam(){if(!pilih||!window.confirm(`Padam ${pilih.nama} bersama peserta dan jawapannya?`))return;setSibuk(true);try{await padamAktiviti(pilih.id);setSemua(s=>s.filter(a=>a.id!==pilih.id));setPilih(null);setNota('Aktiviti dipadam.');}catch(e){setNota(e instanceof Error?e.message:'Gagal memadam aktiviti.')}finally{setSibuk(false)}}
 async function padamJawapan(j:JawapanAktiviti){if(!pilih||!window.confirm(`Padam jawapan ${j.data.muridNama}?`))return;setSibuk(true);try{await padamJawapanAktiviti(pilih.id,j.id);setJawapan(s=>s.filter(x=>x.id!==j.id));setCetak(null);setNota('Jawapan dipadam.');}catch(e){setNota(e instanceof Error?e.message:'Gagal memadam jawapan.')}finally{setSibuk(false)}}
 return <div className="mt-5 space-y-5"><details className="rounded-xl border bg-white p-4"><summary className="cursor-pointer font-bold">Cipta aktiviti</summary><form action={cipta} className="mt-4 grid gap-3 sm:grid-cols-2"><fieldset disabled={sibuk} className="contents">{[['nama','Nama aktiviti','text'],['tarikh','Tarikh aktiviti','date'],['masa','Masa','text'],['tempat','Tempat','text'],['anjuran','Anjuran','text'],['tutup','Tarikh tutup jawapan','date']].map(([k,l,t])=><label key={k} className="text-sm">{l}<input required type={t} name={k} maxLength={500} className="mt-1 block w-full rounded border p-2"/></label>)}<label className="text-sm">Pasukan/skop<select name="skop" className="mt-1 block w-full rounded border p-2">{skop.map(s=><option key={s}>{s}</option>)}</select></label><button disabled={sibuk} className="self-end rounded bg-navy-800 p-2 text-white">Cipta aktiviti</button></fieldset></form></details>
 {nota&&<p role="status" className="rounded bg-navy-50 p-3 text-sm">{nota}</p>}
 <ul className="space-y-2">{semua.map(a=><li key={a.id}><button disabled={sibuk} onClick={()=>void buka(a)} className="w-full rounded-xl border bg-white p-4 text-left"><b>{a.nama}</b><span className="block text-sm">{a.tarikh} · {a.skop} · {a.aktif?'Dibuka':'Ditutup'}</span></button></li>)}</ul>
 {pilih&&<section className="space-y-4 rounded-xl border bg-white p-5"><h2 className="text-xl font-bold">{pilih.nama}</h2><div className="flex flex-wrap gap-4"><Link href={`/kebenaran/${pilih.id}`} target="_blank" className="font-semibold underline">Pautan ibu bapa ↗</Link>{pilih.aktif&&<button disabled={sibuk} onClick={()=>void tutup()} className="text-sm underline">Tutup penerimaan borang</button>}<button disabled={sibuk} onClick={()=>void padam()} className="text-sm text-[#8f2424] underline">Padam aktiviti</button></div><details><summary className="cursor-pointer text-sm font-semibold">Sunting butiran aktiviti</summary><form onSubmit={e=>{e.preventDefault();void sunting(new FormData(e.currentTarget));}} className="mt-3 grid gap-2 sm:grid-cols-2">{[['nama','Nama','text'],['tarikh','Tarikh','date'],['masa','Masa','text'],['tempat','Tempat','text'],['anjuran','Anjuran','text'],['tutup','Tarikh tutup','date']].map(([k,l,t])=><label key={k} className="text-xs">{l}<input required name={k} type={t} defaultValue={String(pilih[k as keyof AktivitiBorang]??'')} className="mt-1 block w-full rounded border p-2 text-sm"/></label>)}<button disabled={sibuk} className="rounded bg-navy-800 p-2 text-sm text-white">Simpan pindaan</button></form></details><p className="text-sm">{peserta.length} peserta · {jawapan.length} jawapan diterima</p>
 <details><summary className="cursor-pointer font-semibold">Tambah peserta secara pukal</summary><p className="mt-2 text-sm">Tampal nama dan No. KP. Sistem memadankan peserta dengan daftar ePBD.</p><textarea disabled={sibuk} value={teks} onChange={e=>{setTeks(e.target.value);setSemak(null)}} rows={5} className="mt-2 w-full rounded border p-2" aria-label="Senarai peserta"/><button disabled={sibuk||!teks.trim()} onClick={()=>void importPeserta(false)} className="mt-2 rounded border p-2">Semak peserta</button>{semak&&<div className="mt-3"><ol className="max-h-60 overflow-auto text-sm">{semak.map(p=><li key={p.murid_id}>{p.nama} · {p.kelas} · {p.no_kp}</li>)}</ol><button disabled={sibuk} onClick={()=>void importPeserta(true)} className="mt-3 rounded bg-navy-800 p-2 text-white">Sahkan peserta</button></div>}</details>
 <details><summary className="cursor-pointer font-semibold">Senarai peserta ({peserta.length})</summary><ol className="mt-2 max-h-64 overflow-auto text-sm">{peserta.map(p=><li key={p.murid_id}>{p.nama} · {p.kelas}</li>)}</ol></details>
 <h3 className="font-bold">Jawapan dan cetakan</h3><ul className="divide-y">{jawapan.map(j=><li key={j.id} className="flex items-center justify-between gap-3 py-3"><span>{j.data.muridNama} · {j.data.kelas}<small className="block">{j.data.bersetuju?'Membenarkan':'Tidak membenarkan'}</small></span><span className="flex gap-3"><button onClick={()=>setCetak(j)} className="text-sm font-semibold underline">Buka cetakan</button><button disabled={sibuk} onClick={()=>void padamJawapan(j)} className="text-sm text-[#8f2424] underline">Padam</button></span></li>)}</ul>
 {cetak&&<CetakAkuan aktiviti={pilih} data={cetak.data}/>}</section>}</div>
}
