import assert from "node:assert/strict";
import { zipSync, strToU8 } from "fflate";
import { kenakanPindaan, type Pindaan } from "../src/data/pindaan.ts";
import { bukaZip } from "../src/data/buka-zip.ts";
const p = (id: string, jenis: Pindaan["jenis"], dari: string, kepada: string | null): Pindaan => ({ id, jenis, dari, kepada, sebab: null, aktif: true, oleh: null, dicipta: id });
const a = ["1", "GURU CONTOH", "GAB", "MATEMATIK"];
const b = ["1", "GURU CONTOH", "GAB", "BAHASA MELAYU"];
const c = ["1", "GURU BAHARU", "GAB", "BAHASA MELAYU"];
const patch = p("1", "ganti_baris", JSON.stringify(a), JSON.stringify(b));
assert.deepEqual(kenakanPindaan(a, [patch]).sel, b);
assert.deepEqual(kenakanPindaan(["2", ...a.slice(1)], [patch]).sel, ["2", ...a.slice(1)]);
assert.deepEqual(kenakanPindaan(a, [patch, p("2", "ganti_baris", JSON.stringify(b), JSON.stringify(c))]).sel, c);
assert.equal(kenakanPindaan(a, [patch, p("2", "buang_baris", a.join(" "), null)]).gugur, true);
assert.deepEqual(kenakanPindaan(a, [p("3", "ganti_baris", "rosak", "[]")]).sel, a);
assert.deepEqual(kenakanPindaan(a, [p("4", "ganti_baris", JSON.stringify(a), JSON.stringify(["", ...a.slice(1)]))]).sel, ["", ...a.slice(1)]);
assert.deepEqual(kenakanPindaan(a, [{ ...patch, aktif: false }]).sel, a);
const zip = zipSync({ "kelas.txt": strToU8("Nama contoh"), "__MACOSX/a.txt": strToU8("abaikan"), "lain.exe": strToU8("abaikan") });
assert.deepEqual(Object.keys(bukaZip(zip)), ["kelas.txt"]);
assert.throws(() => bukaZip(zipSync({ "besar.txt": new Uint8Array(11 * 1024 * 1024) })), /melebihi had/);
assert.throws(() => bukaZip(zipSync(Object.fromEntries(Array.from({ length: 201 }, (_, i) => [`${i}.txt`, strToU8("x")])))), /melebihi had/);
assert.throws(() => bukaZip(new Uint8Array(51 * 1024 * 1024)), /50 MB/);
assert.throws(() => bukaZip(strToU8("bukan zip")));
console.log("12 ujian pindaan dan ZIP lulus");
